### PR TITLE
Move help to the right menu

### PR DESCRIPTION
**Pull request by nono**
Help was moved to the right menu, so it's accessible from any application.

### CODE REVIEW

**Comment by frankrousseau** [comment]
What about including http://qwebirc.org/ ?

**Comment by nono** [comment]
Well, it's a python/zope thing: not easy to put in our stack and can take a lot of RAM. But maybe we can try to see it in action.

**Comment by aenario** [comment]
We could also include the shout server preconfigured for our public chan in our stack (as a Service ?) and a minimalist client in home to allow users to chat with support from their cozy.

**Comment by frankrousseau** [comment]
Thank you @nono

**Comment by nono** [comment]
@kelukelu can you put the new icons for the help menu?

**Comment by kelukelu** [comment]
I can't access my home anymore (node 4 issue on my VM). 
@nono I can give you the sprite. Is that sound good to you ?

**Comment by nono** [comment]
@kelukelu Yes, I should be able to do that

**Comment by kelukelu** [comment]
@nono you're the man ! I will work on it asap.

**Comment by kelukelu** [comment]
@nono please find the svg file here, my good sir (╭ರ‿•́) https://luc.cozycloud.cc/public/files/files/1c8970b0935a9c8622cc2510ca3861c2/attach/sprite-help.svg

**Pull request merged**
