### PR TITLE
Add fonts

### PR DESCRIPTION
**Pull request by m4dz**
This PR:
- add cozy-fonts
- clean index.html

### CODE REVIEW

**Comment by aenario** [comment]
Note to self : on a separate PR we should move the index.html to server/views/index.jade with proper imports.

**Comment by frankrousseau** [comment]
@aenario is it good to merge?

**Comment by aenario** [comment]
I was affraid it will break the changing tab-icon, but it appears we already broke it sometime ago, so good to merge and I will open an issue about that.

**Comment by frankrousseau** [comment]
@aenario Can you handle the merge?

**Comment by aenario** [comment]
yep

**Comment by aenario** [comment]
rebase merged as ebb527c7aa

**Pull request closed without merging**
