### PR TITLE
Fixed: icons. Added: application installation wizard.

### PR DESCRIPTION
**Pull request by jsilvestre**
The commit log is pretty self-explanatory about what I did.

### CODE REVIEW

**Comment by jsilvestre** [comment]
Tests don't pass, but I don't understand why: there are 99 tests and Travis says 99 passed.

**Comment by frankrousseau** [comment]
Big PR :)

**Comment by jsilvestre** [comment]
Do you want me to remove the build?

**Comment by frankrousseau** [comment]
No it's ok but it will require time to review.

**Comment by jsilvestre** [comment]
Ok I don't know what to do. Apparently tests don't pass because moment outputs a warning on stderr. The funny thing is that our code doesn't directly use the deprecated moment's feature.

**Comment by jsilvestre** [comment]
I forgot to mention that this requires those who updated their home recently to re-update their apps. That won't affect those with "pre-icon changes" Home.

**Pull request merged**
