### PR TITLE
Improve English locale

### PR DESCRIPTION
**Pull request by jankeromnes**
Cool project!

I fixed a few errors in the English locale, and slightly changed the wording in some places to make the language sound more idiomatic and natural.

### CODE REVIEW

**Comment by jankeromnes** [comment]
Travis failure doesn't look related to my commit.

**Comment by jankeromnes** [comment]
@frankrousseau, care to have a look? :)

**Comment by frankrousseau** [comment]
Thanks @jankeromnes!

**Comment by jankeromnes** [comment]
Thank you for merging!

**Pull request merged**
