### PR TITLE
Remove app frame after an update or an uninstall

### PR DESCRIPTION
**Pull request by frankrousseau**
To avoid update problem due to browser cache or misleading behaviors, this PR removes the app frame when the app is marked as updating, uninstalled or broken.

### CODE REVIEW

**Comment by clochix** [comment]
Hi @frankrousseau, what's the status of this one ? Who is best fitted to review it ?

**Comment by frankrousseau** [comment]
Yes.

**Comment by aenario** [comment]
Merged with master into development

**Comment by clochix** [comment]
Thanks to both of you, I close this ☺

**Pull request closed without merging**
