### PR TITLE
Ui enhancements

### PR DESCRIPTION
**Pull request by m4dz**
This PR introduces minor changes to Ui:
- manage your apps
  - sort apps when collection changes (#316)
  - add more informations such as app status and website URL
  - improve buttons
  - prepare disk space to receive unit as separated information from the service (another PR is needed in cozy-controller) (#304)
- marketplace
  - improve community app alert
- help
  - add link to relaunch install wizard

### CODE REVIEW

**Comment by frankrousseau** [comment]
Ok it looks great. Can you fix this:

* When an installation is confirmed shows something that confirms that the installation is running (maybe remove the app only when it's installed and display something showing that installation is running and desactivate new install modal for this app).
* add tooltip on config app buttons

**Comment by m4dz** [comment]
> add tooltip on config app buttons

You mean, something like a title attribute on buttons ?

**Comment by frankrousseau** [comment]
yes

**Comment by frankrousseau** [comment]
Another point, your modification don't work well with small screens in the configuration list management.

**Comment by frankrousseau** [comment]
New bug: When an update is complete, it doesn't hide the spinner.

**Comment by m4dz** [comment]
OK, I'm on it

**Comment by m4dz** [comment]
Done :)

**Comment by frankrousseau** [comment]
I think the waiter should be displayed until the installation ends.

**Comment by m4dz** [comment]
Isn't the case? I mean:
- click on the app tile, the waiter is displayed 
- install:
    - success: the tile is removed (and its waiter too, such as its a children node)
    - failed: the waiter is removed

Is it correct?

**Comment by frankrousseau** [comment]
No, it doesn't wait the installation finishes. @aenario I have to leave. I let you finish the review.

**Comment by m4dz** [comment]
Ok, I take a look at it

**Comment by m4dz** [comment]
@frankrousseau, I have a doubt about your request: do you talk about the waiter on the apps tile in the marketplace view or about an update button in the manage your apps view (and, in this case, which button?)?

**Comment by frankrousseau** [comment]
I talk about the waiting the waiter on the tile in the marketplace view.

**Comment by m4dz** [comment]
OK. I've just tested again and I've got the behavior visible in the screenshot below until the tile disappear (when install finishes). I can't reproduce your bug :/…

waiter on tile in marketplace

**Comment by frankrousseau** [comment]
OK don't worry I will show you next week.

**Comment by m4dz** [comment]
Alright (but you merged it too fast, I didnt push the fix for the custom git field install :yum:… I open a new PR for it) :)

**Pull request merged**
