### PR TITLE
Open app from status page on mobile

### LINKED ISSUE #676: On mobile cozy does not open the application in a new tab if asked from status page
On the home, when using a mobile (can be reproduced with Chrome and faking the browser as a Nexus 4), when I click on an application, the app is opened in a new tab (which I guess if the correct behaviour, probably to earn some space).

However, this is not the case when opening an application by clicking on its title (or starting it I think) in the status page : the app is opened in the same page.

### PR DESCRIPTION
**Pull request by m4dz**
Fix  #676

### CODE REVIEW

**Comment by clochix** [comment]
Wow, such reactivity, thanks @m4dz !!!

**Comment by frankrousseau** [comment]
@m4dz could you add comments explaining what it does?

**Comment by m4dz** [comment]
Done (I also added some improvements for scripts loading :wink:)

**Comment by frankrousseau** [comment]
Thank you!

**Pull request merged**
