### PR TITLE
Fix some typos in fr locale

### PR DESCRIPTION
**Pull request by nono**

### CODE REVIEW

**Comment by clochix** [comment]
I think it would be better from now on to use Transifex to improve translations, to prevent conflicts.

**Comment by nono** [comment]
@clochix I can't find how to do that on transifex...

**Comment by nono** [comment]
@clochix it's done on transifex (with your help).

**Comment by clochix** [comment]
You made the changes on Transifex, and I just made an PR with the latest changes in french locale from Transifex, so I think we an close this one without merging ?

**Comment by nono** [comment]
Yes

**Pull request closed without merging**
