### PR TITLE
Wizard component

### PR DESCRIPTION
**Pull request by m4dz**
This PR introduces the wizard component as a Backbone.View that can be used to defines wizards screens in apps (currently in home for the _install app wizard_ and _quick tour helper_).

### CODE REVIEW

**Comment by jsilvestre** [comment]
I'm currently reviewing it ;)

**Comment by m4dz** [comment]
PR is ready for me. I think we could add a tourist.js-like feature that hightlight one (or more) targeted elements for each screen (optionally) but it an be done in another PR.

**Comment by jsilvestre** [comment]
I'm trying the review process for real, see https://github.com/cozy/cozy-home/issues/267 for my functional comments.

**Comment by m4dz** [comment]
Ok for me now :)

**Comment by jsilvestre** [comment]
It looks good to me.

**Comment by jsilvestre** [comment]
@frankrousseau it's merged :)

**Comment by frankrousseau** [comment]
cool :)

**Comment by frankrousseau** [comment]
It looks like a build is missing.

**Pull request merged**
