### PR TITLE
Fix build for node4

### PR DESCRIPTION
**Pull request by nono**

### CODE REVIEW

**Comment by frankrousseau** [comment]
Sorry @nono, it's still failing.

**Comment by nono** [comment]
@frankrousseau yeah, travis is in a bad mood. It can't fetch packages from ubuntu PPA: http://ppa.launchpad.net/. Let's see later if network connectivity is fixed.

**Comment by nono** [comment]
@frankrousseau the issue on travis is fixed and the build is now green.

**Comment by frankrousseau** [comment]
Great, thank you @nono!

**Pull request merged**
